CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    details TEXT,
    headquarters VARCHAR(100),
    office VARCHAR(100),
    in_person BOOLEAN DEFAULT FALSE,
    group_session BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ensure columns exist when table was created earlier without them
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS headquarters VARCHAR(100);
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS office VARCHAR(100);
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS in_person BOOLEAN DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS group_session BOOLEAN DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_schedule_employee_id ON schedule(employee_id);
CREATE INDEX IF NOT EXISTS idx_schedule_user_id ON schedule(user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_start_at ON schedule(start_at);
CREATE INDEX IF NOT EXISTS idx_schedule_end_at ON schedule(end_at);

-- Tabla para Agendas Médicas (disponibilidad de profesionales)
CREATE TABLE IF NOT EXISTS medical_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    modality VARCHAR(20) NOT NULL, -- intramural | telemedicina
    headquarters_id BIGINT,
    office_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    work_days VARCHAR(32) NOT NULL, -- Ej: "L,M,X,J,V"
    start_time VARCHAR(5) NOT NULL, -- HH:mm
    end_time VARCHAR(5) NOT NULL,   -- HH:mm
    appointment_duration INT NOT NULL,
    service_types TEXT, -- JSON o CSV de ids/nombres
    allow_group_session BOOLEAN DEFAULT FALSE,
    requires_referral BOOLEAN DEFAULT FALSE,
    notes TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'VIGENTE',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_med_agenda_employee ON medical_agenda(employee_id);
CREATE INDEX IF NOT EXISTS idx_med_agenda_status ON medical_agenda(status);
CREATE INDEX IF NOT EXISTS idx_med_agenda_active ON medical_agenda(is_active);