-- Versioned migration V2 to apply initial schema when baseline=1

-- (Same content as V1 but versioned as V2 to run after baseline)
CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    details TEXT,
    headquarters VARCHAR(100),
    office VARCHAR(100),
    in_person BOOLEAN DEFAULT FALSE,
    group_session BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE schedule ADD COLUMN IF NOT EXISTS headquarters VARCHAR(100);
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS office VARCHAR(100);
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS in_person BOOLEAN DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS group_session BOOLEAN DEFAULT FALSE;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE schedule ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_schedule_employee_id ON schedule(employee_id);
CREATE INDEX IF NOT EXISTS idx_schedule_user_id ON schedule(user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_start_at ON schedule(start_at);
CREATE INDEX IF NOT EXISTS idx_schedule_end_at ON schedule(end_at);

CREATE TABLE IF NOT EXISTS schedule_config (
    id BIGSERIAL PRIMARY KEY,
    config_type VARCHAR(50) NOT NULL,
    holiday_date DATE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS calendar_exception (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    modality VARCHAR(20) NOT NULL,
    headquarters_id BIGINT,
    office_id BIGINT,
    exception_date DATE NOT NULL,
    start_time VARCHAR(5),
    end_time VARCHAR(5),
    is_full_day BOOLEAN DEFAULT FALSE,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cal_exception_employee ON calendar_exception(employee_id);
CREATE INDEX IF NOT EXISTS idx_cal_exception_date ON calendar_exception(exception_date);

CREATE TABLE IF NOT EXISTS medical_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    modality VARCHAR(20) NOT NULL,
    headquarters_id BIGINT,
    office_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    work_days VARCHAR(32) NOT NULL,
    start_time VARCHAR(5) NOT NULL,
    end_time VARCHAR(5) NOT NULL,
    appointment_duration INT NOT NULL,
    service_types TEXT,
    allow_group_session BOOLEAN DEFAULT FALSE,
    requires_referral BOOLEAN DEFAULT FALSE,
    notes TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'VIGENTE',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN DEFAULT TRUE,
    convenios TEXT,
    can_create_medical_history BOOLEAN DEFAULT FALSE,
    double_shift BOOLEAN DEFAULT FALSE,
    enabled_slots INT,
    agenda_state VARCHAR(20) DEFAULT 'ABIERTA',
    frequency VARCHAR(50),
    created_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_med_agenda_employee ON medical_agenda(employee_id);
CREATE INDEX IF NOT EXISTS idx_med_agenda_status ON medical_agenda(status);
CREATE INDEX IF NOT EXISTS idx_med_agenda_active ON medical_agenda(is_active);

ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS convenios TEXT;
ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS can_create_medical_history BOOLEAN DEFAULT FALSE;
ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS double_shift BOOLEAN DEFAULT FALSE;
ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS enabled_slots INT;
ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS agenda_state VARCHAR(20) DEFAULT 'ABIERTA';
ALTER TABLE medical_agenda ADD COLUMN IF NOT EXISTS frequency VARCHAR(50);
